### ISSUE TITLE
 plot_connections issued error for specific range position

### ISSUE THREAD

**Issue by honghh2018** [cole-trapnell-lab/cicero-release#40] opened 2020-01-09 12:36 UTC
Hi all,
    The error occured when runging function below, ranges at chr17:50236092-50244917 
     plot_connections(conns, "chr17", 50236092, 50244917,
                 gene_model = gene_anno, 
                 coaccess_cutoff = .25, 
                 connection_width = .5, 
                 collapseTranscripts = "longest")
The error showing:
  Error in plot_connections(conns, "chr17", 50236092, 50244917, gene_model = gene_anno,  : 
  No peaks in the specified range, nothing to plot!
But I can sure that chromosome length own 94987271 bases in chr17, and i make conns object  was like below:
sample_genome <- subset(mouse.mm9.genome, V1 == "chr17")
## Usually use the whole mouse.mm9.genome ##
conns <- run_cicero(cicero_cds, sample_genome, sample_num = 100) 
Please give me a tips for this solution.
 Thanks!

**Comment by hpliner** [comment] 2020-01-23 15:08
Hello, thanks for the report. Can you confirm that there are peaks in the exact range you specified?

**Comment by hpliner** [comment] 2020-02-24 13:03
I'm going to close this issue due to lack of reply. Reply/reopen if this continues to be an issue.

**Comment by johannesnicolaus** [comment] 2020-02-26 03:39
Hi, I am also experiencing the same issue. 

I did the following function
```r
plot_connections(conns, "chr2", 60686631, 60709986,
                 gene_model = gene_anno, 
                 coaccess_cutoff = 0, 
                 connection_width = .1, 
                 collapseTranscripts = "longest" )
```

I confirmed the presence of peaks by performing the following:

```r
conns %>%
  filter(grepl("chr2_60686", Peak1)) %>% arrange(desc(coaccess))
```

I found that there are peaks in the region and that the coaccess score is above 0.

I'm not sure what went wrong, but the first time I did it it worked, and then I upgraded Cicero from 1.3.4.5 to 1.3.4.7 and I think this might have something to do with the difference?

My monocle3 version is 0.2.0.

**Comment by hpliner** [comment] 2020-03-09 13:26
@johannesnicolaus Can you post a bit of the output of your second snippet above?

**Comment by johannesnicolaus** [comment] 2020-03-10 03:03
Hi, thanks for your reply.

Sorry, I think it happened because I did not specify regions containing multiple peaks for plotting.

Working fine now, thanks!

**Comment by hpliner** [comment] 2020-03-10 12:29
Great, glad it's resolved!

**Closed as completed by hpliner** 2020-03-10 12:29 UTC
